-- Generated by cheatsheet/extract.py — đừng sửa tay, chạy lại script.
-- sheet grep: 79 entries
BEGIN;
DELETE FROM sheets WHERE slug = 'grep';
INSERT INTO sheets (slug, title, subtitle, badge, description, logo, source_url, links, meta, aliases, layout) VALUES ('grep', 'grep Cheatsheet', 'Global Regular Expression Print', NULL, 'Search text and files using regular expressions.', NULL, 'https://www.gnu.org/software/grep/manual/grep.html', '[{"label": "GNU grep manual", "url": "https://www.gnu.org/software/grep/manual/grep.html"}]'::jsonb, '{"popular_commands": ["grep <pattern> <file>", "-i", "-n", "-r", "-v"]}'::jsonb, ARRAY['egrep', 'grep']::text[], '[{"icon": "🔍", "title": "Basic Usage & Matching", "layout": "grid", "body_cols": 1, "sections": [{"label": "Basic Usage", "kind": "table", "copy_lines": false}, {"label": "Matching Control", "kind": "table", "copy_lines": false}]}, {"icon": "👁️", "title": "Output Control", "layout": "grid", "body_cols": 1, "sections": [{"label": "Formatting & Output", "kind": "table", "copy_lines": false}]}, {"icon": "📁", "title": "Context & File Selection", "layout": "grid", "body_cols": 1, "sections": [{"label": "Context Control", "kind": "table", "copy_lines": false}, {"label": "Directory & File Selection", "kind": "table", "copy_lines": false}]}, {"icon": "🧩", "title": "Regular Expression Reference", "layout": "grid", "body_cols": 1, "sections": [{"label": "Character Classes & Anchors", "kind": "table", "copy_lines": false}, {"label": "Quantifiers & Groups (BRE / ERE / PCRE)", "kind": "table", "copy_lines": false}]}, {"icon": "ℹ️", "title": "Return Status & zgrep", "layout": "grid", "body_cols": 1, "sections": [{"label": "Exit Status", "kind": "rows", "copy_lines": false}, {"label": "Compressed Files (zgrep)", "kind": "table", "copy_lines": false}]}, {"icon": "💡", "title": "Practical Examples", "layout": "grid", "body_cols": 1, "sections": [{"label": "Common Use Cases", "kind": "table", "copy_lines": false}]}]'::jsonb);
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 1, 1, 'Basic Usage & Matching', 'Basic Usage', 'command', 'grep <pattern> <file>', 'Search for a pattern in a specific file', NULL, 'grep "error" app.log', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Basic Usage & Matching › Basic Usage
grep <pattern> <file>
Search for a pattern in a specific file', '7f9857984360bfbf7f9985aa2b805a4df59f8f2e6cf8d0f6419263e105502374', 'Tìm kiếm mẫu chuỗi trong một file cụ thể', 'grep › Basic Usage & Matching › Basic Usage
grep <pattern> <file>
Tìm kiếm mẫu chuỗi trong một file cụ thể
tìm từ khoá trong một file cụ thể
tra cứu chuỗi ký tự trong một tệp
dò nội dung trong một file đơn lẻ', 'ba60096190152e15078fa9bf85b81f87f12e3f41a193f593d3100bc73469a450');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 1, 2, 'Basic Usage & Matching', 'Basic Usage', 'command', 'grep <pattern> <file1> <file2>', 'Search for a pattern in multiple files', NULL, 'grep "error" app.log db.log', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Basic Usage & Matching › Basic Usage
grep <pattern> <file1> <file2>
Search for a pattern in multiple files', '0f9c16a86ce30c2d90f222f07960e3543efb107822ad6483db0da709a5a12b2f', 'Tìm kiếm mẫu chuỗi trong nhiều file cùng lúc', 'grep › Basic Usage & Matching › Basic Usage
grep <pattern> <file1> <file2>
Tìm kiếm mẫu chuỗi trong nhiều file cùng lúc
tìm từ khoá qua nhiều file cùng lúc
tra cứu chuỗi trên danh sách nhiều tệp
dò nội dung ở hai hay nhiều file', '68a9de5ce406fbc556450cc9486361881cb430ebc92c09e21151297157ced8bf');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 1, 3, 'Basic Usage & Matching', 'Basic Usage', 'command', 'cat <file> | grep <pattern>', 'Search from standard input (via pipe)', NULL, 'cat app.log | grep "error"', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Basic Usage & Matching › Basic Usage
cat <file> | grep <pattern>
Search from standard input (via pipe)', '1c3c0cd070b24eea43bfb8958f8c1d43357b3ece59ac81efa665c7e40756d9f7', 'Tìm kiếm chuỗi từ đầu vào chuẩn qua đường ống (pipe)', 'grep › Basic Usage & Matching › Basic Usage
cat <file> | grep <pattern>
Tìm kiếm chuỗi từ đầu vào chuẩn qua đường ống (pipe)
lọc chuỗi từ pipe đầu vào chuẩn
tìm từ khoá qua standard input stdin
tra cứu nội dung nhận từ luồng pipe', '2d1cf6991b24e71c85b0289c08425a8224f4bb9e16eb1ef91829c252de6ccd42');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 1, 'Basic Usage & Matching', 'Matching Control', 'option', '-i', 'Ignore case distinctions in patterns and input data', NULL, 'grep -i "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-i
Ignore case distinctions in patterns and input data', '75be1b227c328e43c024cdf3ae5d682912ef11649ccdd11d312993f2155ace92', 'Tìm kiếm không phân biệt chữ hoa chữ thường', 'grep › Basic Usage & Matching › Matching Control
-i
Tìm kiếm không phân biệt chữ hoa chữ thường
tìm kiếm không phân biệt hoa thường
bỏ qua viết hoa viết thường khi tìm
so khớp chuỗi case insensitive', 'cb8386abba03a25e5e9b08602454b6dec357af0fe18d0e14d60b414e2f32254f');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 2, 'Basic Usage & Matching', 'Matching Control', 'option', '-v', 'Select non-matching lines (invert the match)', NULL, 'grep -v "debug" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-v
Select non-matching lines (invert the match)', '12e775ee5a6ed7ddef4d3e908c6e48e9d6303e9d53cb3621d36a9def5408a1c0', 'Lấy các dòng không khớp với mẫu (đảo ngược kết quả)', 'grep › Basic Usage & Matching › Matching Control
-v
Lấy các dòng không khớp với mẫu (đảo ngược kết quả)
lấy những dòng không chứa từ khoá
đảo ngược kết quả tìm kiếm invert match
loại trừ các dòng chứa chuỗi khớp', 'b042931c5ae4ebc3107371a9af1c586b6d596c52e37b198a16376141d4f84248');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 3, 'Basic Usage & Matching', 'Matching Control', 'option', '-w', 'Match only whole words', NULL, 'grep -w "is" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-w
Match only whole words', 'a663d75ade9c0fa68de0e14f6a4499df621a4cb66678bbac23da249a7c2985fa', 'Chỉ khớp khi đúng nguyên từ hoàn chỉnh (whole word)', 'grep › Basic Usage & Matching › Matching Control
-w
Chỉ khớp khi đúng nguyên từ hoàn chỉnh (whole word)
tìm khớp nguyên từ trọn vẹn
chỉ lấy từ đứng độc lập whole word
so khớp chính xác cả từ không dính chữ khác', '8e55004c6f90e37709864a9c93bb70ac5848a88071022ea336f83292be970621');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 4, 'Basic Usage & Matching', 'Matching Control', 'option', '-x', 'Match only whole lines exactly', NULL, 'grep -x "exact line" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-x
Match only whole lines exactly', '01992546d046a15776bdd39dea88a5f131b9289e20c54ef4e4164dab211a44b1', 'Chỉ khớp khi toàn bộ dòng trùng hoàn toàn với mẫu', 'grep › Basic Usage & Matching › Matching Control
-x
Chỉ khớp khi toàn bộ dòng trùng hoàn toàn với mẫu
tìm khớp chính xác toàn bộ dòng
chỉ lấy dòng trùng hoàn toàn whole line
so khớp nguyên dòng không thừa ký tự', '9a534eef0e5ed66afebd587670696fe5006cc225036c9c307822ed470789d09a');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 5, 'Basic Usage & Matching', 'Matching Control', 'option', '-e <pattern>', 'Specify multiple patterns to match any of them', NULL, 'grep -e "error" -e "warn" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-e <pattern>
Specify multiple patterns to match any of them', '8279949cd90383527a89dc5902da323a9746cd3a26ccba873b73796f5789d5be', 'Chỉ định nhiều mẫu tìm kiếm theo điều kiện HOẶC', 'grep › Basic Usage & Matching › Matching Control
-e <pattern>
Chỉ định nhiều mẫu tìm kiếm theo điều kiện HOẶC
tìm nhiều từ khoá khác nhau cùng lúc
chỉ định nhiều pattern theo điều kiện hoặc
so khớp một trong nhiều chuỗi tìm kiếm', '308cfebae7e87789e059135ee045aeb8f40ba6924d92fc967f582621cbcae127');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 6, 'Basic Usage & Matching', 'Matching Control', 'option', '-f <file>', 'Obtain patterns from a file, one per line', NULL, 'grep -f patterns.txt app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-f <file>
Obtain patterns from a file, one per line', '0a27ab3df3dae4f700df692325255b5f556d855eec55b5ba634b3b267fed364c', 'Đọc danh sách các mẫu tìm kiếm từ file riêng', 'grep › Basic Usage & Matching › Matching Control
-f <file>
Đọc danh sách các mẫu tìm kiếm từ file riêng
đọc danh sách pattern từ file bên ngoài
lấy các từ khoá từ tệp danh sách để tìm
nạp mẫu tìm kiếm từ tệp văn bản', 'b00d5aa9b59265a17ff2e88e3de08dce1213cdec1a8becc3796f4b972030f3a4');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 7, 'Basic Usage & Matching', 'Matching Control', 'option', '-E', 'Interpret pattern as an extended regular expression (ERE)', NULL, 'grep -E "error|warn" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-E
Interpret pattern as an extended regular expression (ERE)', '28a59a6e4f5f0d711284c41508efafd329fbd7898aa83f2257c11a25b17c66c2', 'Dùng biểu thức chính quy mở rộng (ERE - Extended Regex)', 'grep › Basic Usage & Matching › Matching Control
-E
Dùng biểu thức chính quy mở rộng (ERE - Extended Regex)
dùng biểu thức chính quy mở rộng ERE
bật extended regular expression khi tìm
sử dụng regex mở rộng có toán tử hoặc', '4f140b0023110d5595bc40a6129cfea1b51fd5fc8cbe139a8c0479134a6863af');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 8, 'Basic Usage & Matching', 'Matching Control', 'option', '-F', 'Interpret pattern as fixed strings, not regular expressions', NULL, 'grep -F "user*name" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-F
Interpret pattern as fixed strings, not regular expressions', 'bcbb10658922b00a2304e1a832820c0703263b7c6ccf4e158a39b0305fea08dc', 'Tìm chuỗi ký tự thuần, không xử lý regex (fixed string)', 'grep › Basic Usage & Matching › Matching Control
-F
Tìm chuỗi ký tự thuần, không xử lý regex (fixed string)
tìm chuỗi thuần không xử lý regex
coi ký tự đặc biệt là chuỗi thông thường fixed strings
tắt biểu thức chính quy tìm văn bản gốc', '5a6ebc2cb4eef5578fc1a1ec1325439c9230cdd5a6c5ea030314ca364d6a4598');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 9, 'Basic Usage & Matching', 'Matching Control', 'option', '-G', 'Interpret pattern as a basic regular expression (default)', NULL, 'grep -G "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-G
Interpret pattern as a basic regular expression (default)', '8d04a4a3b90fc2e1ef5fb46f78b10c4ab085bc6dc55292aaa4646fb953874939', 'Dùng biểu thức chính quy cơ bản (BRE - Basic Regex mặc định)', 'grep › Basic Usage & Matching › Matching Control
-G
Dùng biểu thức chính quy cơ bản (BRE - Basic Regex mặc định)
dùng biểu thức chính quy cơ bản BRE
bật basic regular expression mặc định
sử dụng regex chuẩn cơ bản', '611ad59480c91e6faf3f2b7351cb36e05db08d6a9e85fc43062f1821a4f9e8b7');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 1, 2, 10, 'Basic Usage & Matching', 'Matching Control', 'option', '-P', 'Interpret pattern as a Perl-compatible regular expression (PCRE)', NULL, 'grep -P "\d+" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Basic Usage & Matching › Matching Control
-P
Interpret pattern as a Perl-compatible regular expression (PCRE)', 'a4050142ad70083da74f116f6f801e26f469bb4cc835ae8ae33778d6b391c93a', 'Dùng biểu thức chính quy tương thích Perl (PCRE)', 'grep › Basic Usage & Matching › Matching Control
-P
Dùng biểu thức chính quy tương thích Perl (PCRE)
dùng regex tương thích Perl PCRE
bật perl compatible regular expression
sử dụng regex nâng cao kiểu perl', 'b4b3101e5278d139b7e54ea198393526976a541b755116ec38523ce4c5a2a4cb');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 1, 'Output Control', 'Formatting & Output', 'option', '-c', 'Print only a count of matching lines per file', NULL, 'grep -c "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-c
Print only a count of matching lines per file', '3497119e524f7577465aab6a4a7d62765e37009d50a3ea6c3db3e54d6eb58533', 'Chỉ đếm và in ra số dòng khớp trong mỗi file', 'grep › Output Control › Formatting & Output
-c
Chỉ đếm và in ra số dòng khớp trong mỗi file
đếm số dòng khớp trong mỗi file
thống kê số lượng kết quả trùng khớp
chỉ hiển thị tổng số dòng tìm được', '1428930003d0ded5e402ae132480950b1f45fca7426176796c0de7a000aa7365');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 2, 'Output Control', 'Formatting & Output', 'option', '-n', 'Prefix each line of output with the 1-based line number', NULL, 'grep -n "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-n
Prefix each line of output with the 1-based line number', 'a62736b4bd7000586be5a44cc16b441f99d965aa5804230cf9f23ae212786032', 'Hiện số thứ tự dòng trước mỗi kết quả tìm thấy', 'grep › Output Control › Formatting & Output
-n
Hiện số thứ tự dòng trước mỗi kết quả tìm thấy
hiện số thứ tự dòng trong file
hiển thị line number trước mỗi kết quả
in kèm vị trí số dòng tìm thấy', '9615451d6bfc9d762905efa0815b6c1432cdc218b9c17c3068857a38a4576af4');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 3, 'Output Control', 'Formatting & Output', 'option', '-b', 'Print the 0-based byte offset before each matching line', NULL, 'grep -b "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-b
Print the 0-based byte offset before each matching line', 'baae2d157649c67d4a37c68b08db828546ab2434981c5bc76c7b00c022de2458', 'In vị trí byte offset trước mỗi dòng kết quả', 'grep › Output Control › Formatting & Output
-b
In vị trí byte offset trước mỗi dòng kết quả
in vị trí byte offset của dòng khớp
hiển thị byte offset trước kết quả
xem toạ độ byte bắt đầu của dòng tìm thấy', 'fe10bd7563445aa1a8ae7546ab5afb91f2d20c9f4814760489b2af3477948e89');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 4, 'Output Control', 'Formatting & Output', 'option', '-H', 'Print the file name for each match', NULL, 'grep -H "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-H
Print the file name for each match', '7a845cd7df0bb110c96c4e701964ee6e3d7865cff6c7b1c1b7104131af77aa2a', 'Luôn in tên file phía trước mỗi dòng kết quả', 'grep › Output Control › Formatting & Output
-H
Luôn in tên file phía trước mỗi dòng kết quả
hiện tên file trước kết quả tìm kiếm
in tên tệp đi kèm mỗi dòng khớp
bắt buộc hiển thị tên file kết quả', 'bc73183eefec4827d9dd0945d56caa37749ff0ca67ef6fd8a06579390da82c11');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 5, 'Output Control', 'Formatting & Output', 'option', '-h', 'Suppress the prefixing of file names on output', NULL, 'grep -h "error" *.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-h
Suppress the prefixing of file names on output', '15c61442f28845c841ed2466d780417443235340050ff541de252fc26f02ea1a', 'Ẩn tên file khỏi kết quả tìm kiếm', 'grep › Output Control › Formatting & Output
-h
Ẩn tên file khỏi kết quả tìm kiếm
ẩn tên file trong kết quả tìm kiếm
không in tên tệp ở đầu ra
tắt hiển thị tên file khi tìm nhiều tệp', '4732cf2261bdea53eb19186a99f62af044b170fcf182a6253925214d8db38c18');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 6, 'Output Control', 'Formatting & Output', 'option', '-l', 'Print only names of files containing matches', NULL, 'grep -l "error" *.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-l
Print only names of files containing matches', '00344b3540e8b92e940e68b80bc881d7fb4660d5b1d39e67feb5b48e85b9c177', 'Chỉ in tên những file có chứa kết quả khớp', 'grep › Output Control › Formatting & Output
-l
Chỉ in tên những file có chứa kết quả khớp
chỉ in tên các file có chứa từ khoá
liệt kê tệp có kết quả khớp
hiển thị danh sách file chứa nội dung tìm', '3b117836b206ea0cd06af4430cf74107eee0fd6c7a37a69a2fdc18df7584c6af');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 7, 'Output Control', 'Formatting & Output', 'option', '-L', 'Print only names of files containing no matches', NULL, 'grep -L "error" *.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-L
Print only names of files containing no matches', '72f61f301dcee7e94327a271d401bc543892e67e6c3ca6cb90e3c3f021d2707f', 'Chỉ in tên những file không chứa kết quả khớp', 'grep › Output Control › Formatting & Output
-L
Chỉ in tên những file không chứa kết quả khớp
chỉ in tên các file không chứa từ khoá
liệt kê tệp không có kết quả khớp
tìm những file không có nội dung này', '4a767e5fb7e944adc0abce6896eb8b0d9853afc11b6796e3f005cfc0b59d0acc');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 8, 'Output Control', 'Formatting & Output', 'option', '-o', 'Show only the part of a line matching the pattern', NULL, 'grep -o "[0-9]\+" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-o
Show only the part of a line matching the pattern', 'f2420a9d64c0d02293aa38feedb3d718be778750309ba788e4a6f68db59ee65c', 'Chỉ hiển thị phần chuỗi khớp với mẫu thay vì toàn bộ dòng', 'grep › Output Control › Formatting & Output
-o
Chỉ hiển thị phần chuỗi khớp với mẫu thay vì toàn bộ dòng
chỉ in phần văn bản khớp mẫu
trích xuất chuỗi regex trùng khớp
lấy riêng phần text match không lấy cả dòng', '23cb4df87abd0d33f5b0b17488ec9ab565fe4205606a8712fc5943c0e5a5024f');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 9, 'Output Control', 'Formatting & Output', 'option', '-q', 'Quiet mode; do not write anything to standard output', NULL, 'grep -q "error" app.log && echo "found"', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-q
Quiet mode; do not write anything to standard output', '61a3c582ef5e6a3291af7fee43e238baba34e1bc2052912219614be4aeccd75d', 'Chế độ im lặng (quiet mode), không xuất kết quả ra stdout', 'grep › Output Control › Formatting & Output
-q
Chế độ im lặng (quiet mode), không xuất kết quả ra stdout
chế độ im lặng không in kết quả ra màn hình
kiểm tra chuỗi tồn tại không xuất stdout
chạy ẩn chỉ lấy exit code thành công hay thất bại', 'ad0f8897cb1711c68ac12a74826cf03fdc4a1e0e3460b9b4f1ae8dca68b0ed93');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 10, 'Output Control', 'Formatting & Output', 'option', '-s', 'Suppress error messages about nonexistent or unreadable files', NULL, 'grep -s "error" missing.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-s
Suppress error messages about nonexistent or unreadable files', '18ff50f4ca97e1d0d65b6aa1a59134111ab853f221fc44110e582b9306e9d37d', 'Ẩn các thông báo lỗi khi file không tồn tại hoặc không đọc được', 'grep › Output Control › Formatting & Output
-s
Ẩn các thông báo lỗi khi file không tồn tại hoặc không đọc được
ẩn thông báo lỗi file không tồn tại
bỏ qua lỗi không đọc được tập tin
tắt cảnh báo file missing hoặc permission denied', '167592c832b4ee044eef61b095aa1ff2cbad3d3477a0c145a71c40358ed87a8a');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 11, 'Output Control', 'Formatting & Output', 'option', '-m <num>', 'Stop reading a file after num matching lines', NULL, 'grep -m 1 "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-m <num>
Stop reading a file after num matching lines', '192bb421333cb1ed7ed16e7bfc0d9169eaefd13785b00347cd362ff18f87f7db', 'Dừng đọc file sau khi tìm thấy <num> dòng khớp', 'grep › Output Control › Formatting & Output
-m <num>
Dừng đọc file sau khi tìm thấy <num> dòng khớp
giới hạn số dòng khớp tối đa dừng tìm kiếm
dừng quét file sau n kết quả trùng khớp
chỉ lấy đúng số lượng dòng match chỉ định', 'c83fe83afb54c1d3fa657aabdf14e7995b72dd936e68331db7c23412eb12c129');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 12, 'Output Control', 'Formatting & Output', 'option', '--color=always', 'Surround matched strings with escape sequences to show color', NULL, 'grep --color=always "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
--color=always
Surround matched strings with escape sequences to show color', '9892270c128ede932be200d592dcddd3acb28bea4866ac702ea2bbeeb7bd8749', 'Luôn tô màu chuỗi khớp bằng mã escape kể cả qua pipe', 'grep › Output Control › Formatting & Output
--color=always
Luôn tô màu chuỗi khớp bằng mã escape kể cả qua pipe
luôn bật tô màu highlight kết quả tìm kiếm
giữ màu sắc chuỗi trùng khớp khi pipe qua chương trình khác
bắt buộc hiển thị màu cho từ khóa match', 'fbc95a2055ee0679c32799d85f2a40461d7fc6c098db1db1cd5c457630fedc6e');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 13, 'Output Control', 'Formatting & Output', 'option', '--label=<name>', 'Provide a fake filename for standard input output', NULL, 'cat file | grep --label=file.txt -H "error"', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
--label=<name>
Provide a fake filename for standard input output', 'c1f72f2c0dd35fe08996110c835646c9741d081d4ecb0979dc1630dcb5196ebc', 'Đặt tên file giả lập <name> khi đọc dữ liệu từ stdin', 'grep › Output Control › Formatting & Output
--label=<name>
Đặt tên file giả lập <name> khi đọc dữ liệu từ stdin
đặt tên file giả định khi tìm kiếm từ stdin
gán nhãn tên tập tin cho đầu vào tiêu chuẩn
hiển thị tên file tùy chỉnh khi nhận pipe input', '1dbae556f9a283261eeb268878bfbd7210221cb226d9adc1e748020ceb6fe2d7');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 14, 'Output Control', 'Formatting & Output', 'option', '-Z', 'Output a zero byte after filename, useful with xargs -0', NULL, 'grep -lZ "error" *.txt | xargs -0 rm', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
-Z
Output a zero byte after filename, useful with xargs -0', '0276058ed80bbb98d2c7ec773985bc9f00bd97fec246d567d64c60f00d18ebdf', 'Xuất byte null sau tên file để kết hợp an toàn với xargs -0', 'grep › Output Control › Formatting & Output
-Z
Xuất byte null sau tên file để kết hợp an toàn với xargs -0
kết thúc tên file bằng ký tự null byte
ngăn cách tên tập tin bằng zero byte cho xargs 0
in byte 0 sau đường dẫn file có chứa khoảng trắng', 'a7fd2c1606bd3105a73183d92edf2acaf8814e294f77c14a320156d11275e25c');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 2, 1, 15, 'Output Control', 'Formatting & Output', 'option', '--line-buffered', 'Use line buffering on output, good for piping', NULL, 'tail -f app.log | grep --line-buffered "error"', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Output Control › Formatting & Output
--line-buffered
Use line buffering on output, good for piping', '7cbb74016223378c74afb6e62137c59e5a6f2e24515a80613cb835204dba06b8', 'Đệm đầu ra theo dòng (line buffering), phù hợp khi truyền pipe liên tục', 'grep › Output Control › Formatting & Output
--line-buffered
Đệm đầu ra theo dòng (line buffering), phù hợp khi truyền pipe liên tục
bật line buffering xuất kết quả ngay theo từng dòng
đẩy dữ liệu qua pipe theo dòng không chờ đầy buffer
xử lý log realtime theo dòng khi kết hợp tail f', 'f233e38d5a32090dc794360ee86577ede056216e6cb3405cf38e7d8b004f1805');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 1, 1, 'Context & File Selection', 'Context Control', 'option', '-A <num>', 'Print num lines of trailing context after matches', NULL, 'grep -A 3 "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Context Control
-A <num>
Print num lines of trailing context after matches', '2a9c1a4729a5d7f5fda9c01157abd9c66c01ced5e04b031cbea4ecfa9de526c6', 'In thêm <num> dòng ngữ cảnh ngay sau dòng khớp', 'grep › Context & File Selection › Context Control
-A <num>
In thêm <num> dòng ngữ cảnh ngay sau dòng khớp
in thêm các dòng phía sau kết quả tìm kiếm
hiển thị ngữ cảnh sau dòng khớp
xem thêm n dòng tiếp theo sau dòng match', '273c0c848bbec51249acab38f333f79380749612aa55681f7d7487ff29384776');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 1, 2, 'Context & File Selection', 'Context Control', 'option', '-B <num>', 'Print num lines of leading context before matches', NULL, 'grep -B 2 "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Context Control
-B <num>
Print num lines of leading context before matches', 'e93a4af151261fb51322435b4eaad788c26a909026b038b3c1362f31608a0895', 'In thêm <num> dòng ngữ cảnh ngay trước dòng khớp', 'grep › Context & File Selection › Context Control
-B <num>
In thêm <num> dòng ngữ cảnh ngay trước dòng khớp
in thêm các dòng phía trước kết quả tìm kiếm
hiển thị ngữ cảnh trước dòng khớp
xem thêm n dòng đứng trước dòng match', 'd30285c45dfe4884876a0d2f1d40cae9556f0f603b57051340964bb0cf5f4c4e');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 1, 3, 'Context & File Selection', 'Context Control', 'option', '-C <num>', 'Print num lines of output context around matches', NULL, 'grep -C 2 "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Context Control
-C <num>
Print num lines of output context around matches', '75ccaaa1300ecce23af61d8efa9ea8909a2f35c42a1c50f9076584a5010ed69f', 'In <num> dòng ngữ cảnh cả trước và sau dòng khớp', 'grep › Context & File Selection › Context Control
-C <num>
In <num> dòng ngữ cảnh cả trước và sau dòng khớp
in các dòng ngữ cảnh xung quanh dòng khớp
hiển thị n dòng cả phía trước lẫn phía sau kết quả
xem nội dung bao quanh dòng match', 'a0f98fa2052b845502295d7fd66b408deb5b94d8a61ebb3aedebfc27887d92c8');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 1, 4, 'Context & File Selection', 'Context Control', 'option', '--group-separator=<str>', 'Use a string to separate groups of context lines', NULL, 'grep -A 1 --group-separator="---" "error" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Context Control
--group-separator=<str>
Use a string to separate groups of context lines', 'e332b36708565b08eea826847f2aaa7d07aa397a361e91ca85e45e435db9fe1a', 'Dùng chuỗi <str> làm dấu phân cách giữa các nhóm dòng ngữ cảnh', 'grep › Context & File Selection › Context Control
--group-separator=<str>
Dùng chuỗi <str> làm dấu phân cách giữa các nhóm dòng ngữ cảnh
đổi ký tự phân tách giữa các khối ngữ cảnh
tùy biến chuỗi phân cách nhóm kết quả tìm kiếm
thay đổi separator ngăn cách các block dòng context', '49207e46fdeb2b4c29acc8a7a1a7a8eadb0d785ea611a9e508db0184abbf7244');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 1, 'Context & File Selection', 'Directory & File Selection', 'option', '-r', 'Read all files under directories recursively', NULL, 'grep -r "error" /var/log/', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
-r
Read all files under directories recursively', 'aadcb6dbe3f8f73cfe64b3e95e42aede081cc3e3e7f9d52b993fbc463542601f', 'Tìm kiếm đệ quy trong toàn bộ file của thư mục', 'grep › Context & File Selection › Directory & File Selection
-r
Tìm kiếm đệ quy trong toàn bộ file của thư mục
tìm kiếm đệ quy toàn bộ thư mục và thư mục con
quét nội dung tất cả file trong folder con
tra cứu từ khóa xuyên suốt cây thư mục recursive', '01a3163348b2740bb645d678e778b7053dd6dfc8a946497fc7f0ad4a2f42ea55');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 2, 'Context & File Selection', 'Directory & File Selection', 'option', '-R', 'Read all files recursively, following all symlinks', NULL, 'grep -R "error" /var/log/', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
-R
Read all files recursively, following all symlinks', 'd004f7934136ebf58495c6d08c07744d6f95aaba00381a62395d7df2e208a727', 'Tìm kiếm đệ quy mọi file và đi theo các liên kết tượng trưng (symlink)', 'grep › Context & File Selection › Directory & File Selection
-R
Tìm kiếm đệ quy mọi file và đi theo các liên kết tượng trưng (symlink)
tìm kiếm đệ quy và đi theo symbolic link
quét toàn bộ thư mục đệ quy follow symlink
tra cứu nội dung file qua liên kết tượng trưng recursive', 'c747dd10607c097b426896bfd1715b79e74774ee230730e314e20f2ceb260323');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 3, 'Context & File Selection', 'Directory & File Selection', 'option', '--include=<glob>', 'Search only files whose base name matches the glob', NULL, 'grep -r --include="*.txt" "error" src/', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
--include=<glob>
Search only files whose base name matches the glob', 'ef1718d3d45479c86370654cb9e7eb9aa275dec4245f9ffa0210aa828e8eb346', 'Chỉ tìm kiếm trong các file có tên khớp mẫu <glob>', 'grep › Context & File Selection › Directory & File Selection
--include=<glob>
Chỉ tìm kiếm trong các file có tên khớp mẫu <glob>
chỉ tìm trong các file có đuôi mở rộng khớp glob
lọc file theo định dạng pattern khi quét thư mục
giới hạn tìm kiếm trong tập hợp file trùng khớp include', '9dfd19425a5397e776116c2c03df97444421229650c03460e9907b292752f94a');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 4, 'Context & File Selection', 'Directory & File Selection', 'option', '--exclude=<glob>', 'Skip files whose base name matches the glob', NULL, 'grep -r --exclude="*.log" "error" src/', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
--exclude=<glob>
Skip files whose base name matches the glob', '26fa90e0d53b73602c5b8cf09358fc2e94ffd6b161b2a33193b51bc60847931e', 'Bỏ qua các file có tên khớp với mẫu <glob>', 'grep › Context & File Selection › Directory & File Selection
--exclude=<glob>
Bỏ qua các file có tên khớp với mẫu <glob>
bỏ qua không tìm các file khớp pattern glob
loại trừ tập tin theo đuôi mở rộng khi tìm kiếm
exclude định dạng file không muốn quét nội dung', '937fc09104bc55ee1cf52f31785df147e43f9cdb73e9881d742754553e483afb');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 5, 'Context & File Selection', 'Directory & File Selection', 'option', '--exclude-dir=<glob>', 'Skip directories whose base name matches the glob', NULL, 'grep -r --exclude-dir=".git" "error" src/', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
--exclude-dir=<glob>
Skip directories whose base name matches the glob', '5561daba4fe6aed64ca89b73bc18871a0b762acb00ece31dc7ec5e4a32abf9f2', 'Bỏ qua các thư mục có tên khớp với mẫu <glob>', 'grep › Context & File Selection › Directory & File Selection
--exclude-dir=<glob>
Bỏ qua các thư mục có tên khớp với mẫu <glob>
bỏ qua thư mục không quét tìm kiếm
loại trừ folder khớp mẫu chỉ định khi duyệt đệ quy
exclude thư mục ẩn git node_modules khi tra cứu', 'e81ae0fa41540550c0c5f2054456685a3c0ed6c8fbf1ab13a89e13656d50490a');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 6, 'Context & File Selection', 'Directory & File Selection', 'option', '-a', 'Process a binary file as if it were text', NULL, 'grep -a "error" binary_file.bin', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
-a
Process a binary file as if it were text', 'eb91f86f787dcde5cbe08974ad2cc68242d0aa4bede928f0937e0565fa7d5b59', 'Xử lý và tìm kiếm file nhị phân (binary) như file văn bản', 'grep › Context & File Selection › Directory & File Selection
-a
Xử lý và tìm kiếm file nhị phân (binary) như file văn bản
tìm kiếm trong file nhị phân như văn bản thường
ép đọc file binary dưới dạng text
quét chuỗi ký tự trong tập tin nhị phân', 'e77d25b0e6c56b112eda82b2b6021fb77bbd34c922ef5646c59227ea20686076');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 7, 'Context & File Selection', 'Directory & File Selection', 'option', '-I', 'Process a binary file as if it did not contain matching data', NULL, 'grep -I "error" src/', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
-I
Process a binary file as if it did not contain matching data', '764e58f53669448a2fb3bcf0c428031a76d2aeb714feec4e5c909ba6df40cf37', 'Tự động bỏ qua các file nhị phân khi quét tìm kiếm', 'grep › Context & File Selection › Directory & File Selection
-I
Tự động bỏ qua các file nhị phân khi quét tìm kiếm
bỏ qua file nhị phân không tìm kiếm
loại trừ tập tin binary chỉ quét file văn bản
không quét các file binary khi tìm kiếm trong thư mục', '1c18537be305a29e4c3ecb16e19f2f817fbbc8856d108aebc763d01dc913214d');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 8, 'Context & File Selection', 'Directory & File Selection', 'option', '--binary-files=<type>', 'Assume data type: binary, text, or without-match', NULL, 'grep --binary-files=without-match "error" file.bin', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
--binary-files=<type>
Assume data type: binary, text, or without-match', '279b523438384807349a938750905db340cb7927330aae8175ae63e90274152e', 'Chỉ định cách xử lý file nhị phân: binary, text hoặc without-match', 'grep › Context & File Selection › Directory & File Selection
--binary-files=<type>
Chỉ định cách xử lý file nhị phân: binary, text hoặc without-match
cấu hình chế độ xử lý file nhị phân
chọn kiểu đọc tập tin binary binary text without-match
tùy chọn đọc file nhị phân hay bỏ qua hoàn toàn', '07cabdf3ce113e00053033aff79b3a7f5eab9769fe7abe3e983bc29829b70f2a');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 9, 'Context & File Selection', 'Directory & File Selection', 'option', '-D <action>', 'Action for devices, FIFOs, and sockets (read or skip)', NULL, 'grep -D skip "error" /dev/', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
-D <action>
Action for devices, FIFOs, and sockets (read or skip)', 'f6644bc03d6641ac37965e00de4c8d5556e4b1d83112cec4b4de3cad6120bd13', 'Chỉ định cách xử lý (read hoặc skip) đối với device, FIFO và socket', 'grep › Context & File Selection › Directory & File Selection
-D <action>
Chỉ định cách xử lý (read hoặc skip) đối với device, FIFO và socket
bỏ qua hoặc đọc các file thiết bị fifo socket
hành động khi gặp device node và socket
xử lý tập tin đặc biệt device fifo khi tìm kiếm', '46761f24ca634f35399276b65ad3ba4cb5180e889c8eaa4ecb87f66f536dc863');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 3, 2, 10, 'Context & File Selection', 'Directory & File Selection', 'option', '-d <action>', 'Action for directories (read, recurse, or skip)', NULL, 'grep -d skip "error" .', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Context & File Selection › Directory & File Selection
-d <action>
Action for directories (read, recurse, or skip)', '90a54ee8901c0785e5523f55bf8036eb469617fdcf301d29029f7d5d41c3df87', 'Chỉ định cách xử lý (read, recurse hoặc skip) khi gặp thư mục', 'grep › Context & File Selection › Directory & File Selection
-d <action>
Chỉ định cách xử lý (read, recurse hoặc skip) khi gặp thư mục
hành động khi gặp thư mục read recurse skip
cấu hình duyệt đệ quy đọc hay bỏ qua directory
chỉ định hướng xử lý thư mục khi tìm kiếm', 'd7243c3134dc9e3884049bda721f6ff625ec35884c9cb20108f5c6eb894ac6b3');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 1, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '^', 'Match the empty string at the beginning of a line', NULL, 'grep "^start" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
^
Match the empty string at the beginning of a line', '0718d0eb41e660259f62c921af817ed6f1707b2afed1ab1f0741c91f7e2971fa', 'Khớp vị trí bắt đầu của một dòng trong regex', 'grep › Regular Expression Reference › Character Classes & Anchors
^
Khớp vị trí bắt đầu của một dòng trong regex
khớp ký tự ở đầu dòng regex
tìm dòng bắt đầu bằng chuỗi ký tự
anchor đầu dòng biểu thức chính quy', '15d95570e88da4ebd53f0a1b47eb67321ae75d37a6d1e0759a6222a28e4da0ba');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 2, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '$', 'Match the empty string at the end of a line', NULL, 'grep "end$" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
$
Match the empty string at the end of a line', '12bc5c99f9fdbe890ec54639e65566c593b8ea5e87b7d74803d3a40bf5ecf862', 'Khớp vị trí kết thúc của một dòng trong regex', 'grep › Regular Expression Reference › Character Classes & Anchors
$
Khớp vị trí kết thúc của một dòng trong regex
khớp ký tự ở cuối dòng regex
tìm dòng kết thúc bằng chuỗi ký tự
anchor cuối dòng biểu thức chính quy', 'cf60f167ab88b28afac3dfe53e7d18f24659f5e459e46b7dcfde2901a3bdab9f');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 3, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '.', 'Match any single character', NULL, 'grep "a.c" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
.
Match any single character', '7777a425c9d892ca7e1f95c71f38cf8163b75ec942778822ad508109930365dc', 'Khớp với bất kỳ một ký tự đơn lẻ nào trong regex', 'grep › Regular Expression Reference › Character Classes & Anchors
.
Khớp với bất kỳ một ký tự đơn lẻ nào trong regex
khớp một ký tự bất kỳ trong regex
đại diện cho ký tự đơn lẻ bất kỳ
ký tự chấm wildcard match ký tự bất kỳ', 'a86c7da780d3c1ebb26e3e4f40a9399f7416bdef8aa3e4997ae7383295e9cd44');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 4, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '[<chars>]', 'Match any single character in the bracket expression', NULL, 'grep "[a-z]" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
[<chars>]
Match any single character in the bracket expression', 'd7908c2af2514dec427c7ef0387b66540da2a65cff0ab2c357a7341565fbfc9a', 'Khớp với một ký tự bất kỳ nằm trong tập hợp [<chars>]', 'grep › Regular Expression Reference › Character Classes & Anchors
[<chars>]
Khớp với một ký tự bất kỳ nằm trong tập hợp [<chars>]
khớp ký tự nằm trong danh sách ngoặc vuông
tập hợp ký tự cho phép trong biểu thức regex
tìm ký tự thuộc tập hợp chỉ định chars', '11033676be54e7997622cac8dbd4287581befacb4a962fb3935fe667f2c303fe');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 5, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '[^<chars>]', 'Match any single character not in the bracket expression', NULL, 'grep "[^0-9]" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
[^<chars>]
Match any single character not in the bracket expression', 'a8ee65a35627d7516415d9b7cd6bd32ce1c7192b642b263c3fc054aa4aaad5f8', 'Khớp với một ký tự bất kỳ KHÔNG nằm trong tập hợp [^<chars>]', 'grep › Regular Expression Reference › Character Classes & Anchors
[^<chars>]
Khớp với một ký tự bất kỳ KHÔNG nằm trong tập hợp [^<chars>]
khớp ký tự không nằm trong danh sách ngoặc vuông
loại trừ tập hợp ký tự trong regex phủ định
tìm ký tự ngoại trừ các ký tự trong ngoặc', '3f58c2d2d01995c5c75441720ec784c6a079f663b1fb0cf8bc4ec28467022b59');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 6, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '[[:digit:]]', 'Match any digit character, equivalent to [0-9]', NULL, 'grep "[[:digit:]]" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
[[:digit:]]
Match any digit character, equivalent to [0-9]', '3fd317e8adcf82a0b60155e7af7adfb8e846c0e291796fcb5da4c035028a67e9', 'Khớp bất kỳ ký tự chữ số nào, tương đương [0-9]', 'grep › Regular Expression Reference › Character Classes & Anchors
[[:digit:]]
Khớp bất kỳ ký tự chữ số nào, tương đương [0-9]
khớp ký tự số tương đương 0 đến 9
lớp ký tự chữ số digit trong regex POSIX
tìm ký tự số bằng posix bracket class', 'd3f8cb3f638d87f98343e4b0566920a5e0725cee0431d0d602c1dc70dcd308df');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 7, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '[[:alpha:]]', 'Match any alphabetic character', NULL, 'grep "[[:alpha:]]" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
[[:alpha:]]
Match any alphabetic character', '05f604d3deff787feaf6cf6def7ad21046451688c8941956e8f47afc3c26b711', 'Khớp bất kỳ ký tự chữ cái nào (alphabet)', 'grep › Regular Expression Reference › Character Classes & Anchors
[[:alpha:]]
Khớp bất kỳ ký tự chữ cái nào (alphabet)
khớp ký tự chữ cái chữ hoa và chữ thường
lớp ký tự bảng chữ cái alpha posix
tìm ký tự chữ cái alphabet trong chuỗi', '2c05c7593fdd8d433c83a6e9c37502011575eb48ef5f66a000a1f6def0085c48');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 8, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '[[:space:]]', 'Match any whitespace character', NULL, 'grep "[[:space:]]" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
[[:space:]]
Match any whitespace character', 'a2afb147e97ba02de51be5e9a9e847e6ec813fde7eedc8defe896bbce2e6b287', 'Khớp bất kỳ ký tự khoảng trắng nào (khoảng trắng, tab, xuống dòng)', 'grep › Regular Expression Reference › Character Classes & Anchors
[[:space:]]
Khớp bất kỳ ký tự khoảng trắng nào (khoảng trắng, tab, xuống dòng)
khớp ký tự khoảng trắng dấu cách tab
lớp ký tự khoảng trắng space posix
tìm khoảng trắng whitespace trong biểu thức regex', 'a3b9e926475bc59963dffda7d29aba59a925420a0fd7563d6c3ec3312d150d95');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 9, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '\b', 'Match the empty string at the edge of a word', NULL, 'grep "\berror\b" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
\b
Match the empty string at the edge of a word', '738859e3cfd76570d5de4645c540114c224fd0d185fe93f61b974144c2b9900c', 'Khớp ranh giới của một từ (word boundary)', 'grep › Regular Expression Reference › Character Classes & Anchors
\b
Khớp ranh giới của một từ (word boundary)
khớp ranh giới từ word boundary
tìm từ đứng độc lập không dính từ khác
ranh giới bắt đầu hoặc kết thúc từ regex', 'c04be1467efd51dc440cad40e2632583db3269dbd547b0f9584da82d026f6c09');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 1, 10, 'Regular Expression Reference', 'Character Classes & Anchors', 'option', '\w', 'Match a word constituent character (alphanumeric or underscore)', NULL, 'grep "\w\+" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Character Classes & Anchors
\w
Match a word constituent character (alphanumeric or underscore)', 'ae95b30f86011e8725397d6414dd377addd975c287213646db948dee29bd3c8b', 'Khớp ký tự thuộc từ (gồm chữ cái, chữ số hoặc dấu gạch dưới)', 'grep › Regular Expression Reference › Character Classes & Anchors
\w
Khớp ký tự thuộc từ (gồm chữ cái, chữ số hoặc dấu gạch dưới)
khớp ký tự từ chữ cái số hoặc gạch dưới
ký tự cấu thành từ alphanumeric underscore
biểu diễn ký tự từ word character regex', 'f6f1561be33095ed5d5386fa9b34c57d563e9a4a1bf4fd9b9196c5925170ff26');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 1, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '*', 'Match the preceding item zero or more times', NULL, 'grep "ab*c" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
*
Match the preceding item zero or more times', 'c05dd1a6642eb438078b3fbcb1becbe6cb0a8ce32acdb1d0f98fb0a604ce5ddf', 'Khớp phần tử đứng trước từ 0 hoặc nhiều lần', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
*
Khớp phần tử đứng trước từ 0 hoặc nhiều lần
khớp 0 hoặc nhiều lần phần tử đứng trước
lặp lại không hoặc nhiều lần regex
ký tự lượng từ sao lặp tùy ý kể cả rỗng', '8ce178437516cebefad83690e63d79c0bea0f8c0b9299d35b081a1e70b370c4d');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 2, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '+', 'Match the preceding item one or more times (ERE only)', NULL, 'grep -E "ab+c" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
+
Match the preceding item one or more times (ERE only)', '5f8c641e208cb04ec80511e0cdadfd42ca5d411f13099e3d1a5f3d434125bc73', 'Khớp phần tử đứng trước từ 1 hoặc nhiều lần (chỉ dùng trong ERE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
+
Khớp phần tử đứng trước từ 1 hoặc nhiều lần (chỉ dùng trong ERE)
khớp 1 hoặc nhiều lần trong ERE mở rộng
lặp lại ít nhất một lần dấu cộng regex ERE
lượng từ lặp một hoặc nhiều lần không cần thoát ký tự', 'dc05f49ddc64db5d5c972110e07f0e3d1577a5993c979074a9aba6824bf21cbd');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 3, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '\+', 'Match the preceding item one or more times (BRE)', NULL, 'grep "ab\+c" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\+
Match the preceding item one or more times (BRE)', 'ad10b10a3434c1d35706e278e0fe67347aa1dd146a299bd79bebbeb84fb94fec', 'Khớp phần tử đứng trước từ 1 hoặc nhiều lần trong chuẩn BRE', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\+
Khớp phần tử đứng trước từ 1 hoặc nhiều lần trong chuẩn BRE
khớp 1 hoặc nhiều lần trong BRE cơ bản
lặp lại ít nhất một lần có escape dấu cộng BRE
dấu cộng thoát ký tự lặp một hoặc nhiều lần regex', '3ffc985ba2d3f4ccc4fa2af4319af618264667171b894664cbd1ba7952d767cf');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 4, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '?', 'Match the preceding item zero or one time (ERE only)', NULL, 'grep -E "ab?c" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
?
Match the preceding item zero or one time (ERE only)', 'b02c43b66211e4aa28bfd609f4e0952a6f693720e924b9ca24e2a8af82ca3fb2', 'Khớp phần tử đứng trước 0 hoặc 1 lần (chỉ dùng trong ERE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
?
Khớp phần tử đứng trước 0 hoặc 1 lần (chỉ dùng trong ERE)
khớp 0 hoặc 1 lần trong ERE mở rộng
phần tử tùy chọn có hoặc không dấu hỏi regex ERE
lượng từ xuất hiện tối đa một lần không cần escape', '4121b652575e619968f10d090c93cc4ff9b32a0b9d11c5245991ec2044c43641');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 5, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '\?', 'Match the preceding item zero or one time (BRE)', NULL, 'grep "ab\?c" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\?
Match the preceding item zero or one time (BRE)', '245b80c2cc9a3b45e3f30ce67e005b6521c5069fc1af883a66f704dad634ceca', 'Khớp phần tử đứng trước 0 hoặc 1 lần trong chuẩn BRE', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\?
Khớp phần tử đứng trước 0 hoặc 1 lần trong chuẩn BRE
khớp 0 hoặc 1 lần trong BRE cơ bản
phần tử tùy chọn có hoặc không escape dấu hỏi BRE
dấu hỏi thoát ký tự lượng từ không hoặc một lần regex', 'd3b23c5f327314bbcd5d318e3c75db420e89c140a4f3108f581b8d3ecef95083');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 6, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '{<n>,<m>}', 'Match the preceding item between n and m times (ERE only)', NULL, 'grep -E "a{2,4}" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
{<n>,<m>}
Match the preceding item between n and m times (ERE only)', 'ce99606dcc1e264d83dab9af8b58539a576b0fa0c4c959ae963f5506cf425500', 'Khớp phần tử đứng trước từ <n> đến <m> lần (chỉ dùng trong ERE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
{<n>,<m>}
Khớp phần tử đứng trước từ <n> đến <m> lần (chỉ dùng trong ERE)
khớp số lần lặp từ n đến m trong ERE mở rộng
giới hạn số lần xuất hiện khoảng n đến m regex ERE
lượng từ khoảng lặp ngoặc nhọn không cần escape', '304352c361bb41b5b0ec5fd91a9f649ef000f8e07ff2c96d6dc02efa9d35a999');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 7, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '\{<n>,<m>\}', 'Match the preceding item between n and m times (BRE)', NULL, 'grep "a\{2,4\}" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\{<n>,<m>\}
Match the preceding item between n and m times (BRE)', '2c1115f7e9e3b78d2555e8d7befdac7b66b9d8a3b8dce1101b722a287100f603', 'Khớp phần tử đứng trước từ <n> đến <m> lần trong chuẩn BRE', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\{<n>,<m>\}
Khớp phần tử đứng trước từ <n> đến <m> lần trong chuẩn BRE
khớp số lần lặp từ n đến m trong BRE cơ bản
khoảng lặp n đến m lần có escape ngoặc nhọn BRE
lượng từ giới hạn số lần lặp thoát ký tự ngoặc nhọn', '5fc89a263ea5cee3fabc4aadd0560e85bc6d8f3a801ed060d938b79ed1141b36');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 8, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '<p1>|<p2>', 'Match either pattern p1 or p2 (ERE only)', NULL, 'grep -E "error|warn" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
<p1>|<p2>
Match either pattern p1 or p2 (ERE only)', '7533f5a421203d0f27414a2b135ced13107a6668e51b8274e2a5452c1af1a9aa', 'Khớp một trong hai mẫu <p1> hoặc <p2> (chỉ dùng trong ERE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
<p1>|<p2>
Khớp một trong hai mẫu <p1> hoặc <p2> (chỉ dùng trong ERE)
khớp một trong hai mẫu hoặc p1 p2 regex ERE
điều kiện hoặc toán tử pipe giữa hai pattern
tìm chuỗi khớp một trong các mẫu chỉ định', '43593d38acec206545d8d7f20f5e89a9ce1855d7069c898623a56dc28e8c2bbf');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 9, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '<p1>\|<p2>', 'Match either pattern p1 or p2 (BRE)', NULL, 'grep "error\|warn" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
<p1>\|<p2>
Match either pattern p1 or p2 (BRE)', 'e48bf2e13371c5e51aa60968fefb9782f48dbd2021a14a3353246b1b7eaca4a0', 'Khớp mẫu <p1> hoặc <p2> trong regex cơ bản (BRE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
<p1>\|<p2>
Khớp mẫu <p1> hoặc <p2> trong regex cơ bản (BRE)
khớp mẫu <p1> hoặc <p2> regex cơ bản
toán tử hoặc OR trong regex BRE
tìm kiếm nhiều điều kiện hoặc gạch đứng escape', 'a5ff85b3c4a462a6db49134957b39e144b2c2927849a99ae6d4c2e49c7854c26');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 10, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '(<pattern>)', 'Group expressions together (ERE only)', NULL, 'grep -E "(ab)+" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
(<pattern>)
Group expressions together (ERE only)', '19d85b295910abb98f624ef71476960e3f4902b57e3c87a5128c0476875f32b6', 'Gom nhóm các biểu thức regex trong chuẩn mở rộng (ERE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
(<pattern>)
Gom nhóm các biểu thức regex trong chuẩn mở rộng (ERE)
gom nhóm biểu thức regex ERE
đóng ngoặc đơn nhóm mẫu regex mở rộng
group các pattern không cần escape', '936228373df0fa4277dbc5d9ff8679c362ee8cb411d5667e02efa6d66930e2fa');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 11, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '\(<pattern>\)', 'Group expressions together (BRE)', NULL, 'grep "\(ab\)\+" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\(<pattern>\)
Group expressions together (BRE)', 'a5004b79f4fadc038622c297a7cd3b43e368236cbdf30d46a45cdc1d12add1fd', 'Gom nhóm các biểu thức trong regex cơ bản (BRE) có escape', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\(<pattern>\)
Gom nhóm các biểu thức trong regex cơ bản (BRE) có escape
gom nhóm regex có gạch chéo BRE
escape ngoặc đơn nhóm mẫu regex cơ bản
group các pattern trong regex BRE', 'a721f3df6523892cc9bcec927448f1ee08fc4e1b5eac6f3d547d913f01f7f3d4');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 12, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '\<n>', 'Backreference: match the text matched by the nth captured group', NULL, 'grep "\([a-z]\)\1" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\<n>
Backreference: match the text matched by the nth captured group', 'a8189dd9326eaf43e4c9e6386ad64370f46823c8ae464e51d930f507a8867998', 'Tham chiếu lại (backreference) nội dung của nhóm đã bắt thứ <n>', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\<n>
Tham chiếu lại (backreference) nội dung của nhóm đã bắt thứ <n>
tham chiếu lại nhóm đã bắt backreference
khớp lại nội dung group thứ n regex
tìm ký tự lặp lại bằng backreference', 'c8beb6c37f35246903fc66ae5e9f0619a479c45bf71d7b3e017152645f7d9ba1');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 13, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '\d', 'Match any decimal digit (PCRE only)', NULL, 'grep -P "\d+" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\d
Match any decimal digit (PCRE only)', 'e8c34a704eeaf1cfc6f701061b4b279aa4a2b633438fa4cbddfc291fc419ceaf', 'Khớp bất kỳ chữ số thập phân nào trong chuẩn PCRE', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\d
Khớp bất kỳ chữ số thập phân nào trong chuẩn PCRE
khớp ký tự chữ số trong regex PCRE
tìm chữ số thập phân bằng ký hiệu d
pattern regex đại diện cho số từ 0 đến 9', '4a560a3373d9833fa6304fc711a199696795c29888c46ac9c97f782022be8607');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 14, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '(?=<pattern>)', 'Positive lookahead: match if followed by pattern (PCRE only)', NULL, 'grep -P "foo(?=bar)" text.txt', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
(?=<pattern>)
Positive lookahead: match if followed by pattern (PCRE only)', '247a6e42019f7f3df13923d4576af50b715e4d9b05c631b321ab9fbd2ee4f9f8', 'Khớp chuỗi nếu phía sau là <pattern> (positive lookahead trong PCRE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
(?=<pattern>)
Khớp chuỗi nếu phía sau là <pattern> (positive lookahead trong PCRE)
khớp chuỗi có mẫu theo sau positive lookahead
điều kiện chuỗi đứng trước positive lookahead
regex kiểm tra phần tử tiếp theo không lấy vào kết quả', 'f9f2ad93323a4a5d040a404230245e0075aab025ad120cc7b3da70388626ae6a');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 4, 2, 15, 'Regular Expression Reference', 'Quantifiers & Groups (BRE / ERE / PCRE)', 'option', '\K', 'Reset the start of the match, keeping only what follows (PCRE only)', NULL, 'grep -P "User: \K\w+" app.log', NULL, NULL, '{"key_style": "code"}'::jsonb, 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\K
Reset the start of the match, keeping only what follows (PCRE only)', 'c605cf2e5fa5b33fc62b74a6269b7c5e3910dac2cbdfae22fd61e5eca051b473', 'Đặt lại điểm bắt đầu khớp, chỉ giữ lại phần phía sau (PCRE)', 'grep › Regular Expression Reference › Quantifiers & Groups (BRE / ERE / PCRE)
\K
Đặt lại điểm bắt đầu khớp, chỉ giữ lại phần phía sau (PCRE)
bỏ qua tiền tố chỉ lấy phần chuỗi phía sau K
reset vị trí bắt đầu khớp regex PCRE
lấy kết quả sau đoạn khớp bằng toán tử K', '1792f8218f91d556ac4e3acda21b2c74a6b4e307409d567a7a4e48e7dfa4517f');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 5, 1, 1, 'Return Status & zgrep', 'Exit Status', 'option', '0', 'One or more lines were selected', NULL, 'grep "error" app.log; echo $?', NULL, NULL, '{"key_style": "plain"}'::jsonb, 'grep › Return Status & zgrep › Exit Status
0
One or more lines were selected', '3a0c742a3ce6d3bad83f2a1baa6e2ee6ec52e441eb253105d7f60cb79f8dc198', 'Mã thoát 0: Tìm thấy ít nhất một dòng khớp', 'grep › Return Status & zgrep › Exit Status
0
Mã thoát 0: Tìm thấy ít nhất một dòng khớp
mã thoát exit status khi tìm thấy kết quả
ý nghĩa mã trả về 0 khi tìm kiếm
exit code 0 khớp ít nhất một dòng', '656d56ea68d3f3d8d0f475f54fa791361f80e285207c04e3eb24173332b2cbaf');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 5, 1, 2, 'Return Status & zgrep', 'Exit Status', 'option', '1', 'No lines were selected', NULL, 'grep "missing" app.log; echo $?', NULL, NULL, '{"key_style": "plain"}'::jsonb, 'grep › Return Status & zgrep › Exit Status
1
No lines were selected', '6bf443b747f05b241533b4d04188d1b27297e77f99a29380744059ce84070a87', 'Mã thoát 1: Không tìm thấy dòng nào khớp', 'grep › Return Status & zgrep › Exit Status
1
Mã thoát 1: Không tìm thấy dòng nào khớp
mã thoát exit code 1 không tìm thấy kết quả
ý nghĩa mã trả về 1 khi không có dòng khớp
exit status 1 không tìm ra chuỗi', 'e20690a532a93ecefe5e76b95d45c2b96b0154f4e20b776eb5409f965bc1984d');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 5, 1, 3, 'Return Status & zgrep', 'Exit Status', 'option', '2', 'An error occurred (e.g., file not found)', NULL, 'grep "error" nonexistent.txt; echo $?', NULL, NULL, '{"key_style": "plain"}'::jsonb, 'grep › Return Status & zgrep › Exit Status
2
An error occurred (e.g., file not found)', 'b346e91b452d5737210812df4a8a4d7036c81a98954799f7d86352e73251d165', 'Mã thoát 2: Xảy ra lỗi (ví dụ không tìm thấy file)', 'grep › Return Status & zgrep › Exit Status
2
Mã thoát 2: Xảy ra lỗi (ví dụ không tìm thấy file)
mã thoát exit code 2 khi gặp lỗi
ý nghĩa mã trả về 2 lỗi không thấy file
exit status 2 báo lỗi thực thi', 'cc9bb48a15279048cbcb69ca28f20c8c706125513b313f687854659bee856d15');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 5, 2, 1, 'Return Status & zgrep', 'Compressed Files (zgrep)', 'command', 'zgrep <pattern> <file.gz>', 'Search compressed files without explicitly uncompressing', NULL, 'zgrep "error" app.log.gz', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Return Status & zgrep › Compressed Files (zgrep)
zgrep <pattern> <file.gz>
Search compressed files without explicitly uncompressing', 'ef461f93af8672dd52ef211305a68fcfb32dcdf67729c9ee4a9330630e7c3495', 'Tìm kiếm chuỗi trực tiếp trong file nén gz mà không cần giải nén', 'grep › Return Status & zgrep › Compressed Files (zgrep)
zgrep <pattern> <file.gz>
Tìm kiếm chuỗi trực tiếp trong file nén gz mà không cần giải nén
tìm chuỗi trong file gz không cần giải nén
tìm nội dung file nén gz trực tiếp
tra cứu file nén gz mà không giải nén ra đĩa', 'c525f1c11e1d444c6f4c1a50113775dc3ef94856378324fe332ffa1841eb4069');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 5, 2, 2, 'Return Status & zgrep', 'Compressed Files (zgrep)', 'command', 'zcat <file.gz> | grep <pattern>', 'Alternative way to search compressed files via pipe', NULL, 'zcat app.log.gz | grep "error"', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Return Status & zgrep › Compressed Files (zgrep)
zcat <file.gz> | grep <pattern>
Alternative way to search compressed files via pipe', '127a495ed5232066c68f5c52bc01770ecb2258e15d38d2a4796992c3fee20264', 'Đọc file nén gz rồi truyền qua pipe để tìm kiếm chuỗi', 'grep › Return Status & zgrep › Compressed Files (zgrep)
zcat <file.gz> | grep <pattern>
Đọc file nén gz rồi truyền qua pipe để tìm kiếm chuỗi
đọc file gz nối pipe để tìm kiếm chuỗi
tìm nội dung file nén thông qua đường ống dẫn pipe
xem nội dung file nén rồi truyền pipe để lọc', '9a6d6162dcc159af1a25d88ed3f553214596ef07306c7d8a25c52dd7e22870d2');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 6, 1, 1, 'Practical Examples', 'Common Use Cases', 'command', 'grep -r --include="*.<ext>" "<pattern>" <dir>', 'Find a pattern recursively in files matching an extension', NULL, 'grep -r --include="*.py" "TODO" .', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Practical Examples › Common Use Cases
grep -r --include="*.<ext>" "<pattern>" <dir>
Find a pattern recursively in files matching an extension', '186cb15338a0bfc4b3b8e9ad042f1a7fd756653b83e521f91e36237de65b48e8', 'Tìm kiếm đệ quy mẫu trong thư mục theo đuôi file chỉ định', 'grep › Practical Examples › Common Use Cases
grep -r --include="*.<ext>" "<pattern>" <dir>
Tìm kiếm đệ quy mẫu trong thư mục theo đuôi file chỉ định
tìm đệ quy theo phần mở rộng đuôi file include
tìm chuỗi trong thư mục chỉ định loại file ext
lọc tìm đệ quy các file có đuôi nhất định', 'a7673d9595748f3caf162bc513c4512a773390f23d2dfe73d6d714ecb5a9a36e');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 6, 1, 2, 'Practical Examples', 'Common Use Cases', 'command', 'grep -c "<pattern>" *.<ext>', 'Count the number of matches in each matching file', NULL, 'grep -c "error" *.log', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Practical Examples › Common Use Cases
grep -c "<pattern>" *.<ext>
Count the number of matches in each matching file', 'd4cf864fb975837a61ab7072e7b6a11ee356070e48198e404d957f1b91670380', 'Đếm số lần xuất hiện của mẫu trong từng file tương ứng', 'grep › Practical Examples › Common Use Cases
grep -c "<pattern>" *.<ext>
Đếm số lần xuất hiện của mẫu trong từng file tương ứng
đếm số dòng khớp mẫu trong từng file
thống kê số lượng kết quả tìm thấy theo file
đếm số lần xuất hiện chuỗi bằng tuỳ chọn c', '5cbaab134f070f4b313afc80a350f1488b93a95a8fab5112b28250c1777bc92c');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 6, 1, 3, 'Practical Examples', 'Common Use Cases', 'command', 'grep -L "<pattern>" <dir>/*.<ext>', 'List files that do NOT contain a specific string', NULL, 'grep -L "deprecated" src/*.c', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Practical Examples › Common Use Cases
grep -L "<pattern>" <dir>/*.<ext>
List files that do NOT contain a specific string', 'b5743b2b870707d02635551a7159bbc0090d9db4ef0a90b34f0ff88e2121bdc4', 'Liệt kê danh sách các file KHÔNG chứa chuỗi chỉ định', 'grep › Practical Examples › Common Use Cases
grep -L "<pattern>" <dir>/*.<ext>
Liệt kê danh sách các file KHÔNG chứa chuỗi chỉ định
liệt kê file không chứa chuỗi cần tìm
tìm danh sách file thiếu từ khoá nhất định
in tên các file không khớp mẫu bằng tuỳ chọn L', 'e6c07cbe9ad7a29640d17f1ae5c48b3fdc17d9047194456a6a9e1b6abdb79d1b');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 6, 1, 4, 'Practical Examples', 'Common Use Cases', 'command', 'zgrep "<pattern>" <file.gz>', 'Search for a pattern across compressed files', NULL, 'zgrep "Exception" /var/log/syslog*.gz', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Practical Examples › Common Use Cases
zgrep "<pattern>" <file.gz>
Search for a pattern across compressed files', '30ee13014c518b0a41b530ea56d82c2ccb54cff43212a0b557b8f1cd1e229c85', 'Tìm kiếm một mẫu trên các file nén gz (hỗ trợ wildcard)', 'grep › Practical Examples › Common Use Cases
zgrep "<pattern>" <file.gz>
Tìm kiếm một mẫu trên các file nén gz (hỗ trợ wildcard)
tìm chuỗi qua nhiều file log nén gz
tra cứu mẫu lỗi trên hàng loạt file nén gz
quét tìm từ khoá qua các file syslog gz', 'e03432769418b7d0d9727ccc11e263cd93b277a3dd4f55a84204fbc8746e08b1');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 6, 1, 5, 'Practical Examples', 'Common Use Cases', 'command', 'grep -oE "<regex>" <file>', 'Extract only matches using an extended regular expression', NULL, 'grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" access.log', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Practical Examples › Common Use Cases
grep -oE "<regex>" <file>
Extract only matches using an extended regular expression', '8a984b9c929876e1bb3f7630385a95494b2b45f838bdafb0fa4b952522c2721e', 'Chỉ trích xuất phần khớp với regex mở rộng (ERE)', 'grep › Practical Examples › Common Use Cases
grep -oE "<regex>" <file>
Chỉ trích xuất phần khớp với regex mở rộng (ERE)
chỉ in phần chuỗi khớp regex mở rộng ERE
trích xuất đoạn khớp regex thay vì cả dòng
lọc lấy chuỗi khớp biểu thức chính quy bằng tuỳ chọn oE', '21192bfa675e401d4e13371d08ad9281ece908bff13be85f3a931a658d394e5c');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 6, 1, 6, 'Practical Examples', 'Common Use Cases', 'command', 'ps aux | grep "[<char>]<rest>"', 'Grep process list without matching the grep command itself', NULL, 'ps aux | grep "[n]ginx"', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Practical Examples › Common Use Cases
ps aux | grep "[<char>]<rest>"
Grep process list without matching the grep command itself', '8998fe2580f2af87fa70ab5bc6a95ca48d2ed8e2790274a9b2d1738ebe1f2cec', 'Lọc danh sách tiến trình mà không hiển thị chính tiến trình lọc này', 'grep › Practical Examples › Common Use Cases
ps aux | grep "[<char>]<rest>"
Lọc danh sách tiến trình mà không hiển thị chính tiến trình lọc này
lọc danh sách tiến trình không kèm chính tiến trình tìm kiếm
tìm tiến trình đang chạy tránh trùng chuỗi tìm
bỏ qua tiến trình hiện tại khi lọc danh sách process', 'fd5de1a3b8e110734d1e1cf1ce94e139241a4de956ee13a267b8ac0dd135fcd8');
INSERT INTO entries (sheet_id, card_pos, section_pos, position, card, section, kind, command, description, details, example, danger, lang, display, embed_text, content_hash, description_vi, embed_text_vi, content_hash_vi) VALUES ((SELECT id FROM sheets WHERE slug = 'grep'), 6, 1, 7, 'Practical Examples', 'Common Use Cases', 'command', 'find <dir> -name "*.<ext>" -print0 | xargs -0 grep "<pattern>"', 'Combine find with xargs for safe filename handling', NULL, 'find . -name "*.txt" -print0 | xargs -0 grep "error"', NULL, NULL, '{"key_style": "cmd"}'::jsonb, 'grep › Practical Examples › Common Use Cases
find <dir> -name "*.<ext>" -print0 | xargs -0 grep "<pattern>"
Combine find with xargs for safe filename handling', '7c551524801d22dec21125e1033df4b32e808b4e633669cd2bff1438e9d6f7ed', 'Kết hợp find và xargs để tìm kiếm an toàn với tên file có dấu cách', 'grep › Practical Examples › Common Use Cases
find <dir> -name "*.<ext>" -print0 | xargs -0 grep "<pattern>"
Kết hợp find và xargs để tìm kiếm an toàn với tên file có dấu cách
tìm chuỗi an toàn với tên file chứa khoảng trắng
quét nội dung file có dấu cách bằng print0 xargs 0
tìm kiếm mẫu trong các file có tên chứa khoảng trống', 'dd0617dd9b691e654b0c53c11fe10f4053b2ffa1c72235a513cbdaedcc8618ab');
COMMIT;
