#!/usr/bin/env bash
# Tạo/bổ sung .env → bật Postgres(pgvector) → kiểm tra Ollama native + pull model → extract HTML
# → dịch tiếng Việt entry mới (agy, nếu có) → nạp schema + seed → embed các văn bản mới.
# Chạy lại an toàn: .env giữ nguyên giá trị cũ, bản dịch/vector đã có không bị làm lại.
set -euo pipefail
cd "$(dirname "$0")/.."

free_port() {  # cổng trống đầu tiên từ $1 trở lên
  local p=$1
  while ss -ltnH "sport = :$p" | grep -q .; do p=$((p + 1)); done
  echo "$p"
}

if [[ ! -f .env ]]; then
  pass=$(openssl rand -base64 36 | tr -dc 'A-Za-z0-9' | head -c 32)
  db_port=$(free_port 5434)
  umask 077
  cat > .env <<EOF
# Generated by scripts/setup.sh on $(date -Iseconds)
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=$db_port
POSTGRES_DB=cheatsheet
POSTGRES_USER=cheatsheet
POSTGRES_PASSWORD=$pass
DATABASE_URL=postgresql://cheatsheet:$pass@127.0.0.1:$db_port/cheatsheet

APP_HOST=127.0.0.1
APP_PORT=$(free_port 8080)
EOF
  echo "✓ generated .env"
fi

# Bổ sung các biến mới cho .env cũ (không ghi đè giá trị đã có)
add_env() { grep -q "^$1=" .env || { echo "$1=$2" >> .env; echo "✓ .env += $1"; }; }
if ! grep -q '^OLLAMA_URL=' .env; then printf '\n# Embedding (Ollama native)\n' >> .env; fi
add_env OLLAMA_URL http://127.0.0.1:11434
add_env EMBED_MODEL bge-m3
add_env EMBED_DIM 1024

docker compose up -d --wait --remove-orphans
set -a; . ./.env; set +a

# Ollama chạy native (systemd), không nằm trong docker compose
command -v ollama >/dev/null || { echo "✗ chưa cài ollama: curl -fsSL https://ollama.com/install.sh | sh" >&2; exit 1; }
curl -sf "$OLLAMA_URL/api/version" >/dev/null || {
  echo "✗ Ollama không chạy ở $OLLAMA_URL — chạy: sudo systemctl enable --now ollama" >&2; exit 1; }
export OLLAMA_HOST=$OLLAMA_URL
ollama list | awk 'NR>1 {print $1}' | grep -qx "$EMBED_MODEL\(:latest\)\?" || ollama pull "$EMBED_MODEL"

uv run -q -m cheatsheet.extract
# translate tự chạy lại extract khi có bản dịch mới; thiếu agy/lỗi thì vẫn tiếp tục với bản dịch đang có
uv run -q -m cheatsheet.translate || echo "⚠ còn entry chưa có bản dịch tiếng Việt (search vẫn chạy, kém chính xác hơn)" >&2
psql_db() { docker compose exec -T db sh -c 'psql -v ON_ERROR_STOP=1 -q -U "$POSTGRES_USER" -d "$POSTGRES_DB"'; }
cat db/schema.sql db/seed.sql | psql_db
uv run -q -m cheatsheet.embed --prune

docker compose exec -T db sh -c 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "TABLE sheet_list" \
  -c "SELECT model, count(*) AS vectors FROM embeddings GROUP BY model"'
